-- return {
--   "MeanderingProgrammer/render-markdown.nvim",
--   dependencies = { "nvim-treesitter/nvim-treesitter", "nvim-tree/nvim-web-devicons" },
--   ---@module 'render-markdown'
--   ---@type render.md.UserConfig
--   opts = {
--     file_types = { "markdown", "Avante" },
--     render_modes = true,
--   },
--   ft = { "markdown", "Avante" },
-- }
